spring:
  datasource:
    url: "jdbc:postgresql://localhost/workbench"
    driver-class-name: "org.postgresql.Driver"
    username: "steiner"
    password: "779151714"
  exposed:
    generate-ddl: true
    show-sql: true

storage:
  file:
    url: "/home/steiner/workspace/workbench/storage"