spring:
  profiles:
    active: login,todolist

  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB

  datasource:
    url: "jdbc:postgresql://localhost/workbench"
    driver-class-name: "org.postgresql.Driver"
    username: "steiner"
    password: "779151714"
  exposed:
    generate-ddl: true
    show-sql: false


server:
  port: 8082
  servlet:
    context-path: "/api"

  tomcat:
    threads:
      max: 4



file:
  storage:
    todolist-url: "/home/steiner/workspace/workbench/storage/todolist"
    daily-attendance-url: "/home/steiner/workspace/workbench/storage/daily-attendance"

app:
  initialize: false