spring:
  datasource:
    url: "jdbc:postgresql://localhost/workbench"
    driver-class-name: "org.postgresql.Driver"
    username: "steiner"
    password: 779151714
  exposed:
    generate-ddl: true
    show-sql: true

jwt:
  secret: "iot.technology"
  issuer: "workbench-login"
  audience: "web"

open:
  urls:
    - "/authenticate"
    - "/user/register"