

jwt:
  secret: "iot.technology"
  issuer: "workbench-login"
  audience: "web"

open:
  urls:
    - "/authenticate"
    - "/user/register"
    - "/todolist/image/download/*"
    - "/daily-attendance/icon/**"